language: java

os: linux

jdk: oraclejdk8

env:
  global:
    - JAVA_OPTS="-Xms256m -Xmx2g"

branches:
  only:
    - master

before_install:
  # Replace 'nexus.codehaus.org' from '.m2/settings.xml' in Travis (see https://github.com/travis-ci/travis-ci/issues/4629#issuecomment-131214465)
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml

script:
  # Build and test with code coverage
  - mvn -B jacoco:prepare-agent install jacoco:report jacoco:report-aggregate

after_success:
  # Publish code coverage in CodeCov
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    rooms:
      secure: IP6uNOvzVR5m1JUiyBmcg0fltTLyZNuucmuy4+GoohGpVGqknpUhsZ/BmdmBv+l3nIIqaCeRvZQfIpHtqgApXkx5rOr11rFsT6Lcq5QHhh3R01+xWrRlJA9DUroNo2YCaELE6dGDm1J6jbinCGRTlfzHR9NLexCLBlQMTc7xCOulh5tppd1NA4iIre6Cmx6GYRg2DVW+0HA6A5VtRwqDhaPZWC7z5SJlImvyXiMtUO8U2ZHUCvhGMRqkW8SvdeB8UDMlNs+fkJKscW/cDbixw7VZsjlJwnm6llmUPdJxHQkIyZxdbyNacBuspujrmEG0I4+s30Q3NiV95g78pjddnDMkSdYK/h2df2Olj94AYX7lLWeydLKvk1arbv3mX5QmZBlpRXyKqCQ1UMUHvSkcirSNuxj6Z10sb0mC3/Y3KNuBE+dL7Y0udXkBc7tEt5dAMHmQRe3JmH4AUNDqUMbZ+aP6jh09JDA4ybny1oC+OiUv4SLTge7Yor4VUwsoFoIVoX0lKFqD2NyIiLkfo+U9FbNR08CYlQeXT8DS2/7kIwg6komEmcFAvvgwATe7yHVb4ZwOhUWbZmPkqqQt7UG8ZX9dmrjLkQLzSbehOXf7AcHl87xGknSx+BssBBMYehRM5XRuoOB2lKGgliqD0aEdZDY8CA3Cq9ZAPmEXEVw8tpc=
    template:
      - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository} [%{branch}] %{result} in %{duration}
    on_success: always
    on_failure: always
    on_pull_requests: true
